// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW1ftO_emVpOiftEEso8MoiewdoUnwTkE',
    appId: '1:44061497287:web:ea165fad6d6392d8f3abe2',
    messagingSenderId: '44061497287',
    projectId: 'cityscout-ec6bb',
    authDomain: 'cityscout-ec6bb.firebaseapp.com',
    storageBucket: 'cityscout-ec6bb.firebasestorage.app',
    measurementId: 'G-9SJ3NVGZ6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatoj9Zn-8D1_qvDQaGd4XWc1NG_iGMH8',
    appId: '1:44061497287:android:cffa3433c3e74b43f3abe2',
    messagingSenderId: '44061497287',
    projectId: 'cityscout-ec6bb',
    storageBucket: 'cityscout-ec6bb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmg5W565oVaXrV2TkdQ1AO5yCkr6KHCnA',
    appId: '1:44061497287:ios:57153bb33b470105f3abe2',
    messagingSenderId: '44061497287',
    projectId: 'cityscout-ec6bb',
    storageBucket: 'cityscout-ec6bb.firebasestorage.app',
    androidClientId: '44061497287-s5j00657servvmp3mm15u6vbhjebvhjk.apps.googleusercontent.com',
    iosClientId: '44061497287-heg5obn0l5uk0afqm5bebnt4lmevbm22.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityScout',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmg5W565oVaXrV2TkdQ1AO5yCkr6KHCnA',
    appId: '1:44061497287:ios:57153bb33b470105f3abe2',
    messagingSenderId: '44061497287',
    projectId: 'cityscout-ec6bb',
    storageBucket: 'cityscout-ec6bb.firebasestorage.app',
    androidClientId: '44061497287-s5j00657servvmp3mm15u6vbhjebvhjk.apps.googleusercontent.com',
    iosClientId: '44061497287-heg5obn0l5uk0afqm5bebnt4lmevbm22.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityScout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW1ftO_emVpOiftEEso8MoiewdoUnwTkE',
    appId: '1:44061497287:web:ef43e9e0f5dc34a3f3abe2',
    messagingSenderId: '44061497287',
    projectId: 'cityscout-ec6bb',
    authDomain: 'cityscout-ec6bb.firebaseapp.com',
    storageBucket: 'cityscout-ec6bb.firebasestorage.app',
    measurementId: 'G-5R0QJWZP19',
  );
}
